### PR TITLE
Document @ProtectedAttribute and replace @ff.noAttribute

### PR DESCRIPTION
**Pull request by mhdirkse**

### CODE REVIEW

**Comment by mhdirkse** [comment]
Merge this PR after https://github.com/ibissource/frank-doc/pull/48. I intend to make this PR ready-for-review after the mentioned PR will have been merged.

**Comment by nielsm5** [comment]
Could you merge the master into your branch, there are merge conflicts.

**Comment by mhdirkse** [comment]
The master has been merged.

**Comment by mhdirkse** [comment]
I did a search in Eclipse to confirm that @ff.noAttribute is really out

**Review by gvanbrakel — APPROVED** [review]

**Review by nielsm5 — APPROVED** [review]

**Pull request merged**
