### PR TITLE
Update GitHub actions/checkout to v4

### PR DESCRIPTION
**Pull request by jkosternl**

### CODE REVIEW

**Comment by tnleeuw** [comment]
Two points I want to raise before approving:
1. None of the workflows that have been updated, has actually been triggered. So while nothing _should_ break I'm still a bit hesitant to approve.
2. Once approved this change should be backported to all branches we are still maintaining. (I'm not entirely certain if that should include 7.7-release or not at this point b/c I'm not sure what the contracts say).

**Comment by jkosternl** [comment]
> Two points I want to raise before approving:

Thanks @tnleeuw, I didn't know about that. I used the checkout action on the Frank-Doc project already. At least, I thought it is used to checkout the project and IAF. 
I will backport it too, when needed. Wasn't aware of that.

**Review by tnleeuw — APPROVED** [review]

**Comment by tnleeuw** [comment]
> > Two points I want to raise before approving:
> 
> Thanks @tnleeuw, I didn't know about that. I used the checkout action on the Frank-Doc project already. At least, I thought it is used to checkout the project and IAF. I will backport it too, when needed. Wasn't aware of that.

Thanks, knowing you already use this version in the Frank!Doc project without need to change anything else makes me feel more confident to approve it here!

**Review by nielsm5 — APPROVED** [review]

**Comment by nielsm5** [comment]
> Two points I want to raise before approving:
> 
> 1. None of the workflows that have been updated, has actually been triggered. So while nothing _should_ break I'm still a bit hesitant to approve.
> 2. Once approved this change should be backported to all branches we are still maintaining. (I'm not entirely certain if that should include 7.7-release or not at this point b/c I'm not sure what the contracts say).

I doubt it will have a significant impact. So I don't think a backport to 7.7/7.8 is required. The only change so far seems to be [partial checkout filters](https://github.com/actions/checkout/pull/1396).

**Pull request merged**
