### PR TITLE
Show ibisstore message count details in adapter status collapsed view

### LINKED ISSUE #779: Number of messages in Adapter overview
**Reporter**
Gerrit

**Is your feature request related to a problem? Please describe.**
I cannot see the the number of messages in messageLog and errorStorage in the collapsed overview of Adapter Status

**Describe the solution you'd like**
I want to able to see the number of messages in errorStorage in Adapter Status without expanding the adapter. There is ample space for it between the number of messages processed and the arrow to expand the adapter.

### PR DESCRIPTION
**Pull request by alisihab**
Closes #779

### CODE REVIEW

**Comment by alisihab** [comment]
image

**Comment by gvanbrakel** [comment]
I think it would visually be better if the start-stop button was to the right of the errorstore/messagelog icons, so that the start-stop buttons align vertically.

**Comment by alisihab** [comment]
I was thinking that it might be better to hide adapter-wise numbers when the adapter view is expanded. What do you think?

**Comment by alisihab** [comment]
- Collapsed
image
- Expanded
image

**Review by gvanbrakel — APPROVED** [review]

**Review by nielsm5 — APPROVED** [review]

**Pull request merged**
