### PR TITLE
Resolve values

### PR DESCRIPTION
**Pull request by mhdirkse**

### CODE REVIEW

**Comment by mhdirkse** [comment]
Please merge https://github.com/ibissource/frank-doc/pull/146 before this PR.

**Review by gvanbrakel — APPROVED** [review]

**Comment by mhdirkse** [comment]
I discussed with @nielsm5. It seems that all {@value ...} occurrences refer to public Java elements. If this is the case, there is no need to merge this PR. The Frank!Doc PR mentioned above modifies the Frank!Doc such that it can work with private Java elements. If there appear to be references to private constants, we can merge this PR.

**Comment by mhdirkse** [comment]
Indeed, no private fields are needed.

**Comment by mhdirkse** [comment]
We need a private Java element to have attribute Adapter.msgLogLevel in the Frank!Doc. Therefore we do need to merge this PR. @gvanbrakel, we discussed about the enum type that is the argument of the attribute setter. The attribute could be included by making that enum public, but that is not the solution because then any place in the Java code can access the enum.

**Review by gvanbrakel — APPROVED** [review]

**Comment by nielsm5** [comment]
ibissource/frank-doc#146 has been merged :)

**Pull request merged**
