### PR TITLE
Properly close files where required in AmazonS3FileSystem

### PR DESCRIPTION
**Pull request by Laurens-makel**
solves #4854

### CODE REVIEW

**Review by tnleeuw — CHANGES_REQUESTED** [review]
Your changes break a lot of Amazon S3 related tests, that you now try to read from closed stream. Please fix the unit tests.

**Comment by Laurens-makel** [comment]
> Your changes break a lot of Amazon S3 related tests, that you now try to read from closed stream. Please fix the unit tests.

Well, I have been backporting my own custom 7.7 fixes/additions on to the master version in my most recent PR's to prevent issues when upgrading in the future.

In these PR's I did not spend any effort on (unit) tests and I do not have the time available to do so.

Could anyone from the core team have a look at the testing part?

**Comment by nielsm5** [comment]
See my proposed changes in #4978.
Also implemented this for FTP and SFTP FileSystems.

**Comment by Laurens-makel** [comment]
> See my proposed changes in #4978. Also implemented this for FTP and SFTP FileSystems.

Seems like a more elegant solution for the problem!

Closing my attempt

**Pull request closed without merging**
