### PR TITLE
Compare Frank!Doc with previous version

### PR DESCRIPTION
**Pull request by mhdirkse**

### CODE REVIEW

**Comment by mhdirkse** [comment]
As this PR is now, the build can fail if the generated Frank!Doc has changed. This happens when text is removed. I think it is better to have the build succeed regardless the changes in the Frank!Doc. Shall I update this PR for that? We can still produce a diff file with the changes.

**Comment by nielsm5** [comment]
Yes, the build should continue

**Comment by mhdirkse** [comment]
The diffs are produced successfully now, but I think they are truncated in the output of the GitHub action. Shall I write the diffs to files and make them available as artifacts?

**Comment by mhdirkse** [comment]
I saw in the git log that this PR has been superseeded. Shall I close this PR?

**Comment by nielsm5** [comment]
> I saw in the git log that this PR has been superseeded. Shall I close this PR?

Yup, closing this.

**Pull request closed without merging**
